PC_MODE = True

SENSOR_CONFIGURED = "TILT"  # "TILT"
ACTUATOR_CONFIGURED = ""  # ""

URL_ONTOLOGY_DEPLOYMENT_LOCAL = "http://localhost:5001"
URL_ONTOLOGY_DEPLOYMENT_CLOUD = "http://35.195.86.253:5001"

ONTOLOGY_SENSOR_NAME = "TiltSensor"
