BASE_URL = "http://localhost:5000/"


API_ACTUATOR_ENDPOINT = "actuators/"
API_ACTUATION_ENDPOINT = "actuations/"

API_SENSORS_ENDPOINT = "sensor/"
API_SENSOR_OBSERVATIONS_ENDPOINT = "observations/"

API_CONTEXT_AWARE_RULES_ENDPOINT = "context-aware-rules/"
API_CONTEXT_AWARE_RULES_EVENT_RULES_ENDPOINT = "event-rules/"
API_EVENT_RULE_TYPE_NAME_ENDPOINT = "event-rule-types/"
API_CONTEXT_AWARE_RULES_CONDITION_RULES_ENDPOINT = "condition-rules/"
API_CONTEXT_AWARE_RULES_RESPONSE_PROCEDURES_ENDPOINT = "response-procedures/"
API_PROCEDURE_TYPE_NAME_ENDPOINT = "procedure-types/"
