version: '3.9'

services:
  grafana:
    container_name: cloud_api_grafana
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    restart: unless-stopped
    env_file:
      - ENV/grafana.env
    volumes:
      - ./ENV/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - private

  postgres:
    image: postgres:11.18-alpine
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - /var/opt/api_modelling_local/pg_data:/var/lib/postgresql/data/pgdata
    networks:
      - private

networks:
  private:
    driver: bridge
